"""
Set of custom values user for Big Data University deployments
"""

from .aws import *

#### BDU config files ##########################################################
with open(CONFIG_ROOT / "bdu.env.json") as env_file:
    BDU_ENV_TOKENS = json.load(env_file)

with open(CONFIG_ROOT / "bdu.auth.json") as env_file:
    BDU_AUTH_TOKENS = json.load(env_file)

### BDU Labs ##################################################################
BDU_LABS_ROOT_URL = BDU_ENV_TOKENS.get('BDU_LABS_ROOT_URL')
BDU_LABS_OAUTH_CLIENT_NAME = BDU_ENV_TOKENS.get('BDU_LABS_OAUTH_CLIENT_NAME')

# BDU Labs API
BDU_LABS_API_URL = BDU_ENV_TOKENS.get('BDU_LABS_API_URL')
BDU_LABS_ACCESS_KEY = BDU_AUTH_TOKENS.get('BDU_LABS_ACCESS_KEY')
BDU_LABS_SECRET_KEY = BDU_AUTH_TOKENS.get('BDU_LABS_SECRET_KEY')

# Segment client key
SEGMENT_KEY = BDU_AUTH_TOKENS.get('SEGMENT_KEY')
CF_PLATFORM_API = BDU_AUTH_TOKENS.get('CF_PLATFORM_API')
CF_PLATFORM_TOKEN_ENDPOINT = BDU_AUTH_TOKENS.get('CF_PLATFORM_TOKEN_ENDPOINT')
CF_PLATFORM_CLIENT_ID = BDU_AUTH_TOKENS.get('CF_PLATFORM_CLIENT_ID')
CF_PLATFORM_CLIENT_SECRET = BDU_AUTH_TOKENS.get('CF_PLATFORM_CLIENT_SECRET')
CF_PLATFORM_USERNAME = BDU_AUTH_TOKENS.get('CF_PLATFORM_USERNAME')
CF_PLATFORM_PASSWORD = BDU_AUTH_TOKENS.get('CF_PLATFORM_PASSWORD')
CF_PLATFORM_CURRENT_OFFER = BDU_AUTH_TOKENS.get('CF_PLATFORM_CURRENT_OFFER')